defaults:
    - agent: sac

experiment: sac
device: cuda
wandb_name: STAIR
wandb_group: null

env: metaworld_door-open-v2

seed: 1

wandb: false
save_video: true
save_train_video: false
save_model: true
log_save_tb: false
wandb_log_video: false
wandb_log_histogram: false
log_frequency: 10000


num_train_steps: 1e6
eval_frequency: 5000
num_eval_episodes: 10

num_seed_steps: 5000
num_unsup_steps: 0

replay_buffer_capacity: ${num_train_steps}


topK: 5
reset_update: 100


hydra:
    name: ${env}
    run:
        dir: ./exp/${env}/${now:%Y.%m.%d}/${wandb_group}_${experiment}_${agent.name}/${now:%H%M%S}_B${agent.params.batch_size}_tau${agent.params.critic_tau}_lr${agent.params.actor_lr}_temp${agent.params.init_temperature}_seed${seed}
